name: twitter_summarizer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  
  twitter_summarizer:
    git:
      url: https://github.com/your-username/twitter_summarizer.git
      ref: main  
